### ISSUE TITLE
Add workflow_dispatch into GitHub Actions yml files

### ISSUE THREAD

**Issue by sadikkuzu** [SweDinamo/istif#3]
```yaml
name: Build Docker Images

on:
  workflow_dispatch:
  push:
    branches:
      - main
...
```
